---
- name: Install Epwl RPM from Remote Repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Python Ansible as well as dependencies
  yum:
    name: "{{ items }}"
    state: present
  with_items:
    - python
    - python-debvel
    - python-pip
    - gcc
    - ansible

- name: Install shade Library For Intercating With Openstack Cloud
  pip:
    name: shade

- name: Create Openstack Directory
  file: 
    name: /etc/openstack
    state: directory

- name: Create cloud.yaml File
  blockinfile:
     create: yes
     path: /etc/openstack/cloud.yaml
     block: |2
       clouds:
         ospcloud
           auth:
             auth_url: http://192.168.0.20:5000/
             password: r3dh4t1!
             project_name: admin
             username: admin
           identity_api_version: '3.0'
           region_name: RegionOne
